---
title: "UpstreamRegulatorPlot"
author: "Da"
date: '`r format(Sys.time(), "%a %b %d %Y - %X")`'
output: html_document
params:
  folder: "/path/to/input/directory"
  data: "/path/to/UpsteamRegulators.csv"
 # number_of_molecules: "4"
---

UpstreamRegulatorPlot:
-----------

This code takes input from the IPA Upstream Analysis table, creates single plot that shows the top 5 upstream regulators of each molecule type ("transcription regulator","phosphatase","enzyme","kinase","cytokine","growth factor","ligand-dependent nuclear receptor","transmembrane receptor") with their Activation Z-score and P value

Usage:
-----------

Run the following code from the command line:
Rscript UpstreamRegulatorPlot_call.R "/path/to/input/directory" "UpsteamRegulators.csv" 

e.g. Rscript UpstreamRegulatorPlot_call.R ../rawData/ lmp.ola_ctrl_upstream_923.csv 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

inputDir <- params$folder
fileName = params$data
#number_of_molecules <- params$number


```

```{r}
library(stringr)
library(dplyr)
library(ComplexHeatmap)
library(here)
library(ggplot2)
theme_set(theme_classic())
```

```{r}

upstream = read.csv(paste0(inputDir, fileName), header = T)

#fileName = "lmp.ola_ctrl_upstream_923.csv"

#upstream = read.csv("../rawData/lmp.ola_ctrl_upstream_923.csv", header = T)

#upstream = read.csv("../processedData/IPA/lmp.ola_ctrl_upstream_923.csv", header = T)
upstream$log10P = -log10(upstream$p.value.of.overlap)
upstream$sign.value = sign(upstream$Activation.z.score) * upstream$log10P

types = c("transcription regulator","phosphatase","enzyme","kinase","cytokine","growth factor","ligand-dependent nuclear receptor","transmembrane receptor") #these are the molecule types that are of interest
myList = list()
for (i in types){
  myList[[i]] = upstream[which(upstream$Molecule.Type==i),]
  myList[[i]] = top_n(x = myList[[i]], n = 5, wt = -p.value.of.overlap)
}

my_data = do.call(dplyr::bind_rows, myList)
my_data = dplyr::select(my_data, c("Upstream.Regulator", "Molecule.Type", "Activation.z.score", "sign.value"))

my_data = my_data[!is.na(my_data$Activation.z.score),]

scl = 2

UpstreamRegulatorPlot = 
ggplot(my_data, aes(fill=Molecule.Type)) +
  geom_bar(aes(x = reorder(Upstream.Regulator, abs(sign.value)), y = sign.value), stat = "identity", position = "dodge") + 
  coord_flip()+ geom_point(aes(x = Upstream.Regulator, y = Activation.z.score*scl),colour="red") +
  scale_y_continuous(sec.axis = sec_axis(~./scl, name = "Activation.z.score")) + 
  theme(legend.position = "top",axis.title.x = element_text(size=13, face="bold", colour = "black"),    
    axis.title.y = element_text(size=13, face="bold", colour = "black"),    
    axis.text.x = element_text(size=7, face="bold", colour = "black"), 
    # axis.text.y = element_text(size=12,  colour = "black"), # unbold
    axis.text.y = element_text(size=7, face="bold", colour = "black"),strip.text = element_text(face="bold", size=8),
    axis.line.x.top = element_line(color = "red"), axis.title.x.top = element_text(color = "red"), 
    axis.text.x.top = element_text(color = "red")) +ylab("sign value (-log10P * sign of activation)") + 
    xlab("Upstream Regulator")+ geom_hline(yintercept = 0, linetype="dotted", color = "darkgrey", size=1) 


pdf(file = paste0(gsub(".csv","",fileName), ".pdf"), width = 9, height = 9)
print(UpstreamRegulatorPlot)
dev.off()
png(file = paste0(gsub(".csv","",fileName), ".png"), width = 8, height = 7, units = 'in',res = 300)
print(UpstreamRegulatorPlot)
dev.off()

```

```{r fig.width=8, fig.height=8}
print(UpstreamRegulatorPlot)
```

